### ISSUE TITLE
Create PSD_monitor for VERDI frontend

### ISSUE THREAD

**Issue by mtbc** [mcvine/acc#61]
Required for next milestone.

**Comment by mtbc** [comment]
Detects 2D position of incident neutrons.

**Comment by yxqd** [comment]
https://github.com/mcvine/mcvine/blob/c06eda8c47d4fa69c1c600c18d17a7aa2467a7e7/packages/legacycomponents/mcstas2/share/McStas-Components/monitors/PSD_monitor.comp
