### ISSUE TITLE
Create Slit component for VERDI optics

### ISSUE THREAD

**Issue by mtbc** [mcvine/acc#62]
Required for next milestone.

**Comment by mtbc** [comment]
A rectangular aperture, the only path through which neutrons may pass.

**Comment by yxqd** [comment]
https://github.com/mcvine/mcvine/blob/c06eda8c47d4fa69c1c600c18d17a7aa2467a7e7/packages/legacycomponents/mcstas2/share/McStas-Components/optics/Slit.comp#L60

**Comment by mtbc** [comment]
Going fine but it would help if I didn't write things like,
```python
x += x + vx * dt
```
:laughing:
